repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.1.0
      hooks:
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: requirements-txt-fixer
    
    - repo: https://github.com/psf/black
      rev: 19.10b0
      hooks:
      - id: black
        args:
          - --line-length=110
    
    - repo: https://gitlab.com/pycqa/flake8
      rev: '3.8.2'
      hooks:
      - id: flake8
        additional_dependencies: [flake8-black]
        args:
          - --isolated
          - --select=C,E,F,W,B
          - --ignore=E128,E203,E501,W503,C901,BLK100
          - --max-line-length=110
          - --max-complexity=20